server:
  port: 8888

management:
  context-path: /admin
  
logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/royalghost/spring-config-server-repo
          basedir: target/config
